### ISSUE TITLE
Agreement on architecture documentation location

### ISSUE THREAD

**Issue by mattkuznicki-ll** [Lasagna-Love-Portal/project-ricotta#49]
Inspired by https://github.com/Lasagna-Love-Portal/project-ricotta/pull/47 - this PR introduces some cloud architecture principles and discussion that applies across Project Ricotta, and not just the project-ricotta repository. Previous to this PR, @iamthebot and @mattkuznicki-ll authored a general architecture proposal covering cloud and other topics as a Google Doc - see the Quick guide for details (not posting here).

Let's determine where cloud and architecture discussion and information germane to the whole Project Ricotta initiative should live, and then move what needs to be moved to reflect that decision.

**Comment by pid1** [comment]
I propose all documentation exists within the repository as plaintext files.
- Discoverability
  - Having a architecture document within the repo allows users to clone the repo and have all of the information they need, rather than needing to consult external documentation at a secondary location.
  - In-repo Markdown can easily be worked on offline.
  - There is no way for document contributors to subscribe to modifications of the architecture document itself. This necessitates a _third_ tool for notifying contributors that the architecture is changed, as there is not a good on-repo way of doing this. Having to consult Slack history or similar increases the time involved, cognitive burden, and contribution burden when making changes.
- Accessibility
  - Plaintext files like Markdown are easier to work with when using a screen reader than Javascript-powered editing platforms.
- Minimize contribution burden
  - Google Docs does not allow for easily proposing and merging changes. In Google Docs, this requires suggesting edits to the document, and subsequently having an individual propose/remove those edits. This becomes fraught when multiple users are simultaneously suggesting edits, and it becomes unclear what edits are to be included in a given revision.
  - To make non-anonymous edits, it requires that the user utilize a Google account. This brings our total account management for effective contribution to three (Github, Slack, Google).
- Preserve historical information
  - Conversations regarding the reasoning behind proposed, abandoned, and merged edits is lost. Performing contributions via PR preserves these historical conversations for future contributors.
  - There is no easy way to diff two versions of a Google Doc at arbitrary points in time. This is trivial with a plaintext file.
- Security
  - Having a public document with edit access open increases the burden when dealing with malicious edits. Malicious Github users opening PRs are far more easily managed, and cannot confuse ongoing work within a PR.
